### ISSUE TITLE
Convert pilot datasets from BarCoding into NWB files

### ISSUE THREAD

**Issue by Ahad-Allen** [AllenInstitute/OpenScopeNWB#129]

**Comment by Ahad-Allen** [comment]
There is an issue with the upload, most likely caused by the change from the old braintv incoming queue to the mindscope one. the corrected upload job is at; http://lims2/jobs?utf8=%E2%9C%93&search[job_queue][]=702123529&commit=Search

**Comment by jeromelecoq** [comment]
@Ahad-Allen to ask @bjhardcastle

**Comment by bjhardcastle** [comment]
@Ahad-Allen all the data is on lims now, it should be ready for conversion. 
I apparently don't have permissions to toggle 'workflow state' in lims, though, so you may have to trigger manually.

**Comment by Ahad-Allen** [comment]
thank you @bjhardcastle! Conversions are running! Will update based on results.

**Comment by jeromelecoq** [comment]
stim table seems to work. Optotagging was crashing but it looks like we might be able to generate the NWB files without mod.

**Comment by Ahad-Allen** [comment]
I was able to generate the files and they pass NWB inspector! /allen/programs/mindscope/workgroups/openscope/openscopedata2022/1274061513/2023-06-13-13-21/nwb_path/1274061513

**Comment by jeromelecoq** [comment]
@Ahad-Allen to upload

**Comment by Ahad-Allen** [comment]
They are on dandi: https://dandiarchive.org/dandiset/000563/draft

**Comment by jeromelecoq** [comment]
Fix mouse id in the files

**Comment by jeromelecoq** [comment]
@rcpeene to check this file

**Comment by jeromelecoq** [comment]
@rcpeene checked the files and we found: 
1. CCF coordinates was not there: Expected
2. Eye tracking was missing. Was not processed. @Ahad-Allen to check jobs. Module not called? 
3. Timestamps for LFP were completely off. All were within 1s? @Ahad-Allen to check if it is in the source. Leading hypothesis is the sub-sampling module. 
4. @rcpeene to double check spike times. Will send notebooks around. @rcpeene will try to share notebook on colab. 

We only ran one NWB files. @Ahad-Allen to run the 2 others and send to @rcpeene to check.

**Comment by Ahad-Allen** [comment]
Conversions for the other sessions are running now.

The problem with eye tracking was caused by a problem where the sync file ended a few frames before the eye tracking. We will manually do a check for these early sessions and trim the eye files last few frames. I was able to generate NWB files with them as a result/

The timestamps for LFP files seem to be off by a factor of 10000? I've asked ben about this since I spoke with him yesterday about LFP times and he mentioned that the way their unit is calculated has changed.

**Comment by Ahad-Allen** [comment]
1276522234 converted, checking files now.
I had a strange error with the other session that I haven't seen before:
'ValueError: Digital filter critical frequencies must be 0 < Wn < 1'
The full traceback is
Traceback (most recent call last):
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/lfp_subsampling/__main__.py", line 142, in <module>
    main()
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/lfp_subsampling/__main__.py", line 137, in main
    output = subsample(mod.args)
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/lfp_subsampling/__main__.py", line 98, in subsample
    lfp_filtered = remove_lfp_offset(lfp_subsampled,
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/lfp_subsampling/subsampling.py", line 197, in remove_lfp_offset
    b, a = butter(filter_order, cutoff_frequency / (sampling_frequency/2), btype='high')
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/scipy/signal/filter_design.py", line 2956, in butter
    return iirfilter(N, Wn, btype=btype, analog=analog,
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/scipy/signal/filter_design.py", line 2424, in iirfilter
    raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1

I think this might be related to the timestamp's seeming ot have different units here.

**Comment by Ahad-Allen** [comment]
I was able to convert the last session as well when skipping lfp subsampling. I will talk to @bjhardcastle and @arjunsridhar12345 to get some more info on the code they're using for the new lfp timestamps to see if we can get that resolved.

**Comment by Ahad-Allen** [comment]
It seems that @bjhardcastle and @arjunsridhar12345 are using something akin to this script https://github.com/egmcbride/dynamic_routing_ephys/blob/7203fed05ad547fb6c3dfd7c7de208f19d56f602/processing/process_LFP.ipynb to generate new timestamps for the lfp. I've asked to get an idea of what exactly has changed with the timestamps that causes this to be required so we have a better understanding of what's going on with the data.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add notebook here

**Comment by Ahad-Allen** [comment]
The notebook was less relevant but it is present at https://gist.github.com/bjhardcastle/e972d59f482a549f312047221cd8eccb. We already use the event_timestamps file, so this is not the issue. The problem is that the open ephys pipeline no longer returns the proper values in lfp_timestamps.npy It should be returning a list of timestamps that have a stride of 12, but instead the stride is very random. Jerome and I worked on this yesterday. I have emailed the open ephys team about this.

**Comment by Ahad-Allen** [comment]
The open ephys team got back to me. The time_stamps.npy file now contains timestamps rather than sample numbers. I think we should be able to reverse engineer the sample numbers from this, as it is simple to do so if we have the 0th index from the times.

**Comment by jeromelecoq** [comment]
@Ahad-Allen copy the email here.

**Comment by Ahad-Allen** [comment]
![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/e44c705f-afa6-45f5-b98b-60e358ce9696)

I will grab some data on timestamps to verify this and well as the deltas we discussed

**Comment by Ahad-Allen** [comment]
There are also some weird outliers of delta values smaller than .0003 


![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/ef841a1f-05f3-4159-bc0a-46e7fae0c5a6)

**Comment by Ahad-Allen** [comment]
Contacted Josh about these values and asked him who the best person to schedule a meeting with if needed would be.
