### ISSUE TITLE
6 sessions from mice 660986 661749 did not generate NWB files

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#138]

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add correction error

**Comment by Ahad-Allen** [comment]
Error is as follows: 
Traceback (most recent call last):
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/stimulus_table/__main__.py", line 117, in <module>
    main()
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/stimulus_table/__main__.py", line 111, in main
    output = build_stimulus_table(**mod.args)
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/stimulus_table/__main__.py", line 37, in build_stimulus_table
    sync_dataset = EcephysSyncDataset.factory(sync_h5_path)
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/ecephys/file_io/ecephys_sync_dataset.py", line 186, in factory
    obj.load(path)
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/allensdk/brain_observatory/sync_dataset.py", line 159, in load
    self.meta_data = eval(self.dfile['meta'][()])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/allen/programs/mindscope/workgroups/openscope/ahad/Conda_env/openscopenwb/lib/python3.8/site-packages/h5py/_hl/group.py", line 328, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'meta' doesn't exist)"

**Comment by Ahad-Allen** [comment]
All the sessions for 660986 are up now(the problem was the main directory had a second h5 file in it, causing my code to point to the wrong file). Only mouse 661749 remains. This one appears to be related to an issue with generating the stim table, looking into it now.

**Comment by jeromelecoq** [comment]
for 661749, we are not sure why stim sync of photodiode is missing. @Ahad-Allen is looking into stim strings. 
And will reach out to Shiella to check why this was passed.

**Comment by jeromelecoq** [comment]
It looks like the data is fine for this mouse. But we need to package the NWB regardless. 
@Ahad-Allen will look into modify the SDK to flag this file but generate it. Likely a PR on AllenSDK. 

The pipeline should report this error in the log.

**Comment by jeromelecoq** [comment]
@ahad to send code where photodiode is used to @jeromelecoq to review

**Comment by Ahad-Allen** [comment]
I was able to generate the files and upload them for sess 1254161187. We will need to run some kind of verification to make sure the times look ok!

**Comment by Ahad-Allen** [comment]
@rcpeene looked over the times and they seemed to be consistent with other sessions. I have uploaded all the sessions to dandi! :)
